// <auto-generated />
using System;
using Dorian.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dorian.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503204928_AddNutritionModule")]
    partial class AddNutritionModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dorian.Modules.Access.Domain.Entities.AccessPass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("QrCodeValue")
                        .IsUnique();

                    b.ToTable("access_passes", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Access.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckedInByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CheckedInByUserId");

                    b.HasIndex("BranchId", "CheckedInAt");

                    b.HasIndex("CustomerId", "CheckedInAt");

                    b.ToTable("check_ins", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Auditing.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Branches.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("MapUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "Av. Abelardo J Andrade y Reinaldo Chico Peñaherrera",
                            City = "Cuenca",
                            Code = "CEBOLLAR",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 28, DateTimeKind.Unspecified).AddTicks(5670), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MapUrl = "https://www.google.com/maps/search/?api=1&query=Av.%20Abelardo%20J%20Andrade%20y%20Reinaldo%20Chico%20Pe%C3%B1aherrera%2C%20Cuenca%2C%20Ecuador",
                            Name = "El Cebollar",
                            OpeningHours = "Lun a Vie 06:00 - 22:00 | Sab 08:00 - 14:00",
                            PhoneNumber = "0990001001"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Address = "Av. Gonzales Suárez y Jijón de Caamaño",
                            City = "Cuenca",
                            Code = "GONSUAREZ",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 28, DateTimeKind.Unspecified).AddTicks(5697), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MapUrl = "https://www.google.com/maps/search/?api=1&query=Av.%20Gonzales%20Su%C3%A1rez%20y%20Jij%C3%B3n%20de%20Caama%C3%B1o%2C%20Cuenca%2C%20Ecuador",
                            Name = "Gonzáles Suárez",
                            OpeningHours = "Lun a Vie 06:00 - 22:00 | Sab 08:00 - 14:00",
                            PhoneNumber = "0990001002"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Address = "Octavio Chacón Moscoso y Cornelio Vintimilla",
                            City = "Cuenca",
                            Code = "PARQUEIND",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 28, DateTimeKind.Unspecified).AddTicks(5700), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MapUrl = "https://www.google.com/maps/search/?api=1&query=Octavio%20Chac%C3%B3n%20Moscoso%20y%20Cornelio%20Vintimilla%2C%20Cuenca%2C%20Ecuador",
                            Name = "Parque Industrial",
                            OpeningHours = "Lun a Vie 06:00 - 22:00 | Sab 08:00 - 14:00",
                            PhoneNumber = "0990001003"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Address = "Av. Loja y Rodrigo de Triana",
                            City = "Cuenca",
                            Code = "ELTIEMPO",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 28, DateTimeKind.Unspecified).AddTicks(5703), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MapUrl = "https://www.google.com/maps/search/?api=1&query=Av.%20Loja%20y%20Rodrigo%20de%20Triana%2C%20Cuenca%2C%20Ecuador",
                            Name = "El Tiempo",
                            OpeningHours = "Lun a Vie 06:00 - 22:00 | Sab 08:00 - 14:00",
                            PhoneNumber = "0990001004"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Address = "Calle Simón Bolívar",
                            City = "Azogues",
                            Code = "AZOGUES",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 28, DateTimeKind.Unspecified).AddTicks(5707), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MapUrl = "https://www.google.com/maps/search/?api=1&query=Calle%20Sim%C3%B3n%20Bol%C3%ADvar%2C%20Azogues%2C%20Ecuador",
                            Name = "Azogues",
                            OpeningHours = "Lun a Vie 06:00 - 21:00 | Sab 08:00 - 13:00",
                            PhoneNumber = "0990001005"
                        });
                });

            modelBuilder.Entity("Dorian.Modules.Classes.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClassSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "ClassSessionId")
                        .IsUnique();

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Classes.Domain.Entities.ClassSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TrainerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "StartTime");

                    b.ToTable("class_sessions", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.BodyMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("BoneMassKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("ChestCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("HipCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("LeftArmCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("LeftCalfCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("LeftLegCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MuscleMassKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("NeckCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("ResidualMassKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("RightArmCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("RightCalfCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("RightLegCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("ShouldersCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WaistCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "MeasuredAt");

                    b.ToTable("body_measurements", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.BodyProgressPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "TakenAt");

                    b.ToTable("body_progress_photos", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActiveMembershipEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActiveMembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActiveMembershipStartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveMembershipId");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.CustomerFitnessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<int>("FocusMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<int>("GymType")
                        .HasColumnType("integer");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IncludeCardio")
                        .HasColumnType("boolean");

                    b.Property<int>("NotificationIntensity")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredTrainingTime")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("TargetWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("TrainingDaysSerialized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("customer_fitness_profiles", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 31, DateTimeKind.Unspecified).AddTicks(1572), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gym customer",
                            Name = "Customer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 31, DateTimeKind.Unspecified).AddTicks(1574), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gym trainer",
                            Name = "Trainer"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 31, DateTimeKind.Unspecified).AddTicks(1575), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Front desk staff",
                            Name = "Reception"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 31, DateTimeKind.Unspecified).AddTicks(1576), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Branch administrator",
                            Name = "BranchAdmin"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 31, DateTimeKind.Unspecified).AddTicks(1577), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Platform super administrator",
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Dorian.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Identity.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Memberships.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "Name");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Nutrition.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("CarbsGrams")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FatGrams")
                        .HasColumnType("integer");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("ProteinGrams")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("meal_items", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Nutrition.Domain.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DayOfWeek");

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Nutrition.Domain.Entities.NutritionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CarbsGrams")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DailyCaloriesTarget")
                        .HasColumnType("integer");

                    b.Property<string>("DietaryRestrictions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FatGrams")
                        .HasColumnType("integer");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("ProteinGrams")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WaterLitersTarget")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("nutrition_profiles", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Promotions.Domain.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "StartsAt");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.ExerciseCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("Equipment")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroup");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("exercise_catalog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2004), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ejercicio base para desarrollar fuerza y masa en el pecho.",
                            Difficulty = 2,
                            Equipment = 3,
                            MuscleGroup = 1,
                            Name = "Press de banca plano",
                            Slug = "press-banca-plano"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2015), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Activa la porcion superior del pecho con recorrido controlado.",
                            Difficulty = 1,
                            Equipment = 2,
                            MuscleGroup = 1,
                            Name = "Press inclinado con mancuernas",
                            Slug = "press-inclinado-mancuernas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2019), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aislamiento para estirar y contraer el pecho.",
                            Difficulty = 1,
                            Equipment = 2,
                            MuscleGroup = 1,
                            Name = "Aperturas con mancuernas",
                            Slug = "aperturas-mancuernas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2021), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movimiento multiarticular para pecho y triceps.",
                            Difficulty = 3,
                            Equipment = 1,
                            MuscleGroup = 1,
                            Name = "Fondos en paralelas",
                            Slug = "fondos-paralelas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2024), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mejora la amplitud dorsal y la tecnica de traccion.",
                            Difficulty = 1,
                            Equipment = 5,
                            MuscleGroup = 2,
                            Name = "Jalon al pecho",
                            Slug = "jalon-pecho"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2026), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Desarrolla espalda media y control postural.",
                            Difficulty = 2,
                            Equipment = 3,
                            MuscleGroup = 2,
                            Name = "Remo con barra",
                            Slug = "remo-barra"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2028), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fortalece la espalda con tension constante.",
                            Difficulty = 1,
                            Equipment = 5,
                            MuscleGroup = 2,
                            Name = "Remo sentado en polea",
                            Slug = "remo-polea"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2029), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trabaja cadena posterior y control lumbar.",
                            Difficulty = 2,
                            Equipment = 3,
                            MuscleGroup = 2,
                            Name = "Peso muerto rumano",
                            Slug = "peso-muerto-rumano"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2030), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Patron rey para fuerza y potencia del tren inferior.",
                            Difficulty = 2,
                            Equipment = 3,
                            MuscleGroup = 3,
                            Name = "Sentadilla libre",
                            Slug = "sentadilla-libre"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2032), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aumenta volumen de cuadriceps con buena estabilidad.",
                            Difficulty = 1,
                            Equipment = 4,
                            MuscleGroup = 3,
                            Name = "Prensa de piernas",
                            Slug = "prensa-piernas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2034), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ejercicio unilateral para piernas y estabilidad.",
                            Difficulty = 1,
                            Equipment = 2,
                            MuscleGroup = 3,
                            Name = "Zancadas caminando",
                            Slug = "zancadas-caminando"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2035), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Enfocado en isquiotibiales y control de rodilla.",
                            Difficulty = 1,
                            Equipment = 4,
                            MuscleGroup = 3,
                            Name = "Curl femoral",
                            Slug = "curl-femoral"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2036), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fortalece hombros y estabilidad del core.",
                            Difficulty = 2,
                            Equipment = 3,
                            MuscleGroup = 4,
                            Name = "Press militar",
                            Slug = "press-militar"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2037), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aisla el deltoide medio para amplitud visual.",
                            Difficulty = 1,
                            Equipment = 2,
                            MuscleGroup = 4,
                            Name = "Elevaciones laterales",
                            Slug = "elevaciones-laterales"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2039), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mejora la salud escapular y deltoides posterior.",
                            Difficulty = 1,
                            Equipment = 5,
                            MuscleGroup = 4,
                            Name = "Face pulls",
                            Slug = "face-pulls"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2041), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Combina empuje y rotacion para hombro completo.",
                            Difficulty = 2,
                            Equipment = 2,
                            MuscleGroup = 4,
                            Name = "Arnold press",
                            Slug = "arnold-press"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2045), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movimiento base para fuerza de biceps.",
                            Difficulty = 1,
                            Equipment = 3,
                            MuscleGroup = 5,
                            Name = "Curl con barra",
                            Slug = "curl-barra"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2077), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trabaja braquial y antebrazo.",
                            Difficulty = 1,
                            Equipment = 2,
                            MuscleGroup = 5,
                            Name = "Curl martillo",
                            Slug = "curl-martillo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2079), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mayor estiramiento para hipertrofia de biceps.",
                            Difficulty = 2,
                            Equipment = 2,
                            MuscleGroup = 5,
                            Name = "Curl inclinado",
                            Slug = "curl-inclinado"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000020"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2080), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tension continua durante todo el recorrido.",
                            Difficulty = 1,
                            Equipment = 5,
                            MuscleGroup = 5,
                            Name = "Curl en cable",
                            Slug = "curl-cable"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000021"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2082), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aislamiento para la porcion larga del triceps.",
                            Difficulty = 2,
                            Equipment = 3,
                            MuscleGroup = 6,
                            Name = "Press frances",
                            Slug = "press-frances"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000022"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2083), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movimiento controlado para congestion del triceps.",
                            Difficulty = 1,
                            Equipment = 5,
                            MuscleGroup = 6,
                            Name = "Extensiones en polea",
                            Slug = "extensiones-polea"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2085), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ejercicio accesible para iniciar trabajo de triceps.",
                            Difficulty = 1,
                            Equipment = 6,
                            MuscleGroup = 6,
                            Name = "Fondos en banco",
                            Slug = "fondos-banco"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000024"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2086), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aislamiento ligero con enfoque tecnico.",
                            Difficulty = 1,
                            Equipment = 2,
                            MuscleGroup = 6,
                            Name = "Patada de triceps",
                            Slug = "patada-triceps"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000025"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2087), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movimiento basico para abdomen superior.",
                            Difficulty = 1,
                            Equipment = 11,
                            MuscleGroup = 7,
                            Name = "Crunch en colchoneta",
                            Slug = "crunch-colchoneta"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000026"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2088), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mejora estabilidad del core.",
                            Difficulty = 1,
                            Equipment = 1,
                            MuscleGroup = 7,
                            Name = "Plancha frontal",
                            Slug = "plancha-frontal"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000027"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2090), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trabaja abdomen inferior y control lumbo-pelvico.",
                            Difficulty = 2,
                            Equipment = 11,
                            MuscleGroup = 7,
                            Name = "Elevaciones de piernas",
                            Slug = "elevaciones-piernas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000028"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2092), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Activa oblicuos y resistencia del core.",
                            Difficulty = 1,
                            Equipment = 1,
                            MuscleGroup = 7,
                            Name = "Russian twist",
                            Slug = "russian-twist"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000029"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2093), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Principal constructor de gluteo y potencia de cadera.",
                            Difficulty = 2,
                            Equipment = 3,
                            MuscleGroup = 8,
                            Name = "Hip thrust",
                            Slug = "hip-thrust"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000030"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2094), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Activacion inicial y tecnica de extension de cadera.",
                            Difficulty = 1,
                            Equipment = 1,
                            MuscleGroup = 8,
                            Name = "Puente de gluteos",
                            Slug = "puente-gluteos"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000031"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2096), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aisla gluteo mayor con control.",
                            Difficulty = 1,
                            Equipment = 5,
                            MuscleGroup = 8,
                            Name = "Patada de gluteo en polea",
                            Slug = "patada-gluteo-polea"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000032"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2097), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Enfasis en gluteo medio y estabilidad.",
                            Difficulty = 1,
                            Equipment = 4,
                            MuscleGroup = 8,
                            Name = "Abduccion de cadera",
                            Slug = "abduccion-cadera"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000033"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2098), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cardio de baja intensidad para gasto calorico sostenido.",
                            Difficulty = 1,
                            Equipment = 9,
                            MuscleGroup = 9,
                            Name = "Caminata en cinta",
                            Slug = "caminata-cinta"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000034"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2100), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trabajo cardiovascular de impacto bajo.",
                            Difficulty = 1,
                            Equipment = 8,
                            MuscleGroup = 9,
                            Name = "Bicicleta estatica",
                            Slug = "bicicleta-estatica"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000035"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2101), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cardio de cuerpo completo con enfoque tecnico.",
                            Difficulty = 2,
                            Equipment = 10,
                            MuscleGroup = 9,
                            Name = "Remo ergometro",
                            Slug = "remo-ergometro"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000036"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2103), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Condicionamiento intenso de cuerpo completo.",
                            Difficulty = 3,
                            Equipment = 1,
                            MuscleGroup = 9,
                            Name = "Burpees",
                            Slug = "burpees"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000037"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2104), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ejercicio global de empuje y estabilidad.",
                            Difficulty = 1,
                            Equipment = 1,
                            MuscleGroup = 10,
                            Name = "Flexiones",
                            Slug = "flexiones"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000038"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2105), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movimiento funcional para tren inferior y core.",
                            Difficulty = 1,
                            Equipment = 2,
                            MuscleGroup = 10,
                            Name = "Sentadilla goblet",
                            Slug = "sentadilla-goblet"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000039"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2106), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Potencia, cardio y cadena posterior.",
                            Difficulty = 2,
                            Equipment = 7,
                            MuscleGroup = 10,
                            Name = "Kettlebell swing",
                            Slug = "kettlebell-swing"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000040"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2107), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Core dinamico con respuesta cardiovascular.",
                            Difficulty = 1,
                            Equipment = 1,
                            MuscleGroup = 10,
                            Name = "Mountain climbers",
                            Slug = "mountain-climbers"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000041"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2112), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trabajo unilateral y coordinacion.",
                            Difficulty = 1,
                            Equipment = 6,
                            MuscleGroup = 3,
                            Name = "Step-up en banco",
                            Slug = "step-up-banco"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000042"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 3, 20, 49, 28, 30, DateTimeKind.Unspecified).AddTicks(2113), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aislamiento dorsal y control escapular.",
                            Difficulty = 2,
                            Equipment = 5,
                            MuscleGroup = 2,
                            Name = "Pull over en polea",
                            Slug = "pull-over-polea"
                        });
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingDayId", "Order")
                        .IsUnique();

                    b.ToTable("training_exercises", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId", "Order")
                        .IsUnique();

                    b.ToTable("training_phases", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<int>("FocusMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("training_plans", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPlanDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Intensity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TrainingWeekId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingWeekId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("training_days", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TrainingPhaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPhaseId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("training_weeks", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.WorkoutActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CaloriesEstimated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TrainingDayId");

                    b.ToTable("workout_activities", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.WorkoutExerciseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("WorkoutActivityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroup");

                    b.HasIndex("WorkoutActivityId");

                    b.ToTable("workout_exercise_logs", (string)null);
                });

            modelBuilder.Entity("Dorian.Modules.Access.Domain.Entities.AccessPass", b =>
                {
                    b.HasOne("Dorian.Modules.Customers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dorian.Modules.Access.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("Dorian.Modules.Branches.Domain.Entities.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dorian.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CheckedInByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dorian.Modules.Customers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.BodyMeasurement", b =>
                {
                    b.HasOne("Dorian.Modules.Customers.Domain.Entities.Customer", "Customer")
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.BodyProgressPhoto", b =>
                {
                    b.HasOne("Dorian.Modules.Customers.Domain.Entities.Customer", "Customer")
                        .WithMany("BodyProgressPhotos")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Dorian.Modules.Memberships.Domain.Entities.Membership", "ActiveMembership")
                        .WithMany()
                        .HasForeignKey("ActiveMembershipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dorian.Modules.Identity.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Dorian.Modules.Customers.Domain.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveMembership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.CustomerFitnessProfile", b =>
                {
                    b.HasOne("Dorian.Modules.Customers.Domain.Entities.Customer", "Customer")
                        .WithOne("FitnessProfile")
                        .HasForeignKey("Dorian.Modules.Customers.Domain.Entities.CustomerFitnessProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Dorian.Modules.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Dorian.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dorian.Modules.Identity.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Dorian.Modules.Identity.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dorian.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dorian.Modules.Nutrition.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("Dorian.Modules.Nutrition.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("Items")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingExercise", b =>
                {
                    b.HasOne("Dorian.Modules.Training.Domain.Entities.ExerciseCatalog", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dorian.Modules.Training.Domain.Entities.TrainingPlanDay", "TrainingDay")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingDay");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPhase", b =>
                {
                    b.HasOne("Dorian.Modules.Training.Domain.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("Phases")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPlan", b =>
                {
                    b.HasOne("Dorian.Modules.Customers.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPlanDay", b =>
                {
                    b.HasOne("Dorian.Modules.Training.Domain.Entities.TrainingWeek", "TrainingWeek")
                        .WithMany("Days")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingWeek");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingWeek", b =>
                {
                    b.HasOne("Dorian.Modules.Training.Domain.Entities.TrainingPhase", "TrainingPhase")
                        .WithMany("Weeks")
                        .HasForeignKey("TrainingPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPhase");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.WorkoutActivity", b =>
                {
                    b.HasOne("Dorian.Modules.Training.Domain.Entities.TrainingPlanDay", "TrainingDay")
                        .WithMany("WorkoutActivities")
                        .HasForeignKey("TrainingDayId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TrainingDay");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.WorkoutExerciseLog", b =>
                {
                    b.HasOne("Dorian.Modules.Training.Domain.Entities.WorkoutActivity", "WorkoutActivity")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutActivity");
                });

            modelBuilder.Entity("Dorian.Modules.Customers.Domain.Entities.Customer", b =>
                {
                    b.Navigation("BodyMeasurements");

                    b.Navigation("BodyProgressPhotos");

                    b.Navigation("FitnessProfile");
                });

            modelBuilder.Entity("Dorian.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Dorian.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Dorian.Modules.Nutrition.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPhase", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPlan", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingPlanDay", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("WorkoutActivities");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.TrainingWeek", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Dorian.Modules.Training.Domain.Entities.WorkoutActivity", b =>
                {
                    b.Navigation("ExerciseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
